export default function user(state={}, action) {
  if (action.type == 'userSignin') {
    return state.user
  }
  else if (action.type == 'userSignup') {
    console.log("TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST TEST GROS TEST")
    return state.user
  }
  else {
    return state;
  }
}
